// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Gateway.Startup.ConfigureServices(Microsoft.Extensions.DependencyInjection.IServiceCollection)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Gateway.Startup.Configure(Microsoft.AspNetCore.Builder.IApplicationBuilder,Microsoft.AspNetCore.Hosting.IWebHostEnvironment)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:Gateway.Persistence.AppDbContext.OnModelCreating(Microsoft.EntityFrameworkCore.ModelBuilder)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:Gateway.Controllers.BestellungController.BestellungAufgegebenAsync(Gateway.Core.Models.BestellungAufgegeben)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:Gateway.Core.Security.Tokens.AccessToken.#ctor(System.String,System.Int64,Gateway.Core.Security.Tokens.RefreshToken)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:Gateway.Persistence.DatabaseSeed.Seed(Gateway.Persistence.AppDbContext,Gateway.Core.Security.Hashing.IPasswordHasher)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:Gateway.Persistence.UserRepository.AddAsync(Gateway.Core.Models.User,Gateway.Core.Models.ERole[])~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:Gateway.Security.Tokens.TokenHandler.#ctor(Microsoft.Extensions.Options.IOptions{Gateway.Security.Tokens.TokenOptions},Gateway.Security.Tokens.SigningConfigurations,Gateway.Core.Security.Hashing.IPasswordHasher)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:Gateway.Services.AuthenticationService.CreateAccessTokenAsync(System.String,System.String)~System.Threading.Tasks.Task{Gateway.Core.Services.Communication.TokenResponse}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:Gateway.Services.AuthenticationService.RefreshTokenAsync(System.String,System.String)~System.Threading.Tasks.Task{Gateway.Core.Services.Communication.TokenResponse}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:Gateway.Services.UserService.CreateUserAsync(Gateway.Core.Models.User,Gateway.Core.Models.ERole[])~System.Threading.Tasks.Task{Gateway.Core.Services.Communication.CreateUserResponse}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1052:Static holder types should be Static or NotInheritable", Justification = "<Pending>", Scope = "type", Target = "~T:Gateway.Persistence.DatabaseSeed")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:Gateway.Services.UserService.CreateUserAsync(Gateway.Core.Models.User,Gateway.Core.Models.ERole[])~System.Threading.Tasks.Task{Gateway.Core.Services.Communication.CreateUserResponse}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA2227:Collection properties should be read only", Justification = "<Pending>", Scope = "member", Target = "~P:Gateway.Core.Models.Role.UsersRole")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA2227:Collection properties should be read only", Justification = "<Pending>", Scope = "member", Target = "~P:Gateway.Core.Models.User.UserRoles")]
